import moment from "moment";

const fakeData = [
  {
    id: 1,
    buyer: "0x0713d86D5b29719B7E374B5B74aEB61d14b4B281",
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: null,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB03",
    owner: "0x149E966E4EC4F5B89B8752a3630aC200d7F39615",
  },
  {
    id: 2,
    buyer: "0x149E966E4EC4F5B89B8752a3630aC200d7F39615",
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "IVI",
    },
    expiredEndIn: 361346700,
    startingExpiredTime: moment("Wed Aug 10 2022 23:43:26 GMT+0700"),
    status: "DB03",
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/IVI-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    owner: "0x0713d86D5b29719B7E374B5B74aEB61d14b4B281",
  },
  {
    id: 3,
    buyer: "0x149E966E4EC4F5B89B8752a3630aC200d7F39615",
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "IHI",
    },
    expiredEndIn: 3600000,
    startingExpiredTime: moment("Wed Aug 10 2022 23:43:26 GMT+0700"),
    status: "DB06",
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/IHI-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    owner: "0x0713d86D5b29719B7E374B5B74aEB61d14b4B281",
  },
  {
    id: 4,
    buyer: "0x0713d86D5b29719B7E374B5B74aEB61d14b4B281",
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: null,
    startingExpiredTime: moment(),
    status: "DB01",
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    owner: "0x149E966E4EC4F5B89B8752a3630aC200d7F39615",
  },
  {
    id: 5,
    buyer: "0x0713d86D5b29719B7E374B5B74aEB61d14b4B281",
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: null,
    startingExpiredTime: moment(),
    status: "granted",
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    owner: "0x149E966E4EC4F5B89B8752a3630aC200d7F39615",
  },
  {
    id: 6,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "IVI",
    },
    expiredEndIn: 3600000,
    startingExpiredTime: moment("Wed Aug 10 2022 23:43:26 GMT+0700"),
    status: "available",
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/IVI-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    owner: "",
  },
  {
    id: 7,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: null,
    startingExpiredTime: moment(),
    status: "granted",
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    owner: "",
  },
  {
    id: 8,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "IVI",
    },
    expiredEndIn: 3600000,
    startingExpiredTime: moment("Wed Aug 10 2022 23:43:26 GMT+0700"),
    status: "available",
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/IVI-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    owner: "",
  },
  {
    id: 9,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: null,
    startingExpiredTime: moment(),
    status: "granted",
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
  },
  {
    id: 10,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB02",
    owner: "0x149E966E4EC4F5B89B8752a3630aC200d7F39615",
  },
  {
    id: 11,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB02",
    owner: "0x149E966E4EC4F5B89B8752a3630aC200d7F39615",
  },
  {
    id: 12,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB02",
    owner: "0x149E966E4EC4F5B89B8752a3630aC200d7F39615",
  },
  {
    id: 13,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB02",
    owner: "0x149E966E4EC4F5B89B8752a3630aC200d7F39615",
  },
  {
    id: 14,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB02",
    owner: "0x149E966E4EC4F5B89B8752a3630aC200d7F39615",
  },
  {
    id: 15,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB03",
    owner: "0x149E966E4EC4F5B89B8752a3630aC200d7F39615",
  },
  {
    id: 16,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB03",
    owner: "0x149E966E4EC4F5B89B8752a3630aC200d7F39615",
  },
  {
    id: 17,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB01",
    owner: "0x0713d86D5b29719B7E374B5B74aEB61d14b4B281",
  },
  {
    id: 18,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB03",
    owner: "0x0713d86D5b29719B7E374B5B74aEB61d14b4B281",
  },
  {
    id: 19,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB02",
    owner: "0x0713d86D5b29719B7E374B5B74aEB61d14b4B281",
  },
  {
    id: 20,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB02",
    owner: "0x0713d86D5b29719B7E374B5B74aEB61d14b4B281",
  },
  {
    id: 21,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366841",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB01",
    owner: "0x0713d86D5b29719B7E374B5B74aEB61d14b4B281",
  },
  {
    id: 22,
    buyer: null,
    image: require("@images/trade/datahub/item-example-image.png"),
    avatar: require("@images/trade/datahub/item-example-avatar.png"),
    favoriteCount: 1700,
    name: "TenViMetamask",
    tags: [
      "healthcare",
      "medicine",
      "hospital",
      "healthyliving",
      "mentalhealth",
    ],
    code: "IVIE6366849",
    currentBid: {
      value: 23.1,
      name: "USDT",
    },
    expiredEndIn: 36000000,
    startingExpiredTime: moment(),
    viewed: 1000,
    currencyLogo: require("@images/trade/datahub/usdt-currency.png"),
    detail: {
      overview: {
        patientName: "Nguyễn Thị Hoa",
        gt_tuoi: "Nữ, 31 tuổi",
        ma_nb: "1810068153",
        ma_hs: "1800123004",
        qr: "",
        healthFacilities: "Bệnh viện Quân Y 110",
        service: [
          "Khám lân sàng tổng quát (Nội, ngoại, da liễu, TMH, Mắt, RHM) Glucose máu",
          "Định lượng Cholesterol toàn phần (Máu)",
        ],
        examinationTime: "22/10/2020",
        reappointment: "22/07/2021",
      },
      examination: {
        doctorName: "PGS.TS. Nguyễn Viết Nhung",
        phongKham: "Phòng khám số 1",
        khoa: "Khoa khám chữa bệnh theo yêu cầu",
      },
    },
    status: "DB02",
    owner: "0x0713d86D5b29719B7E374B5B74aEB61d14b4B281",
  },
];

export default fakeData;
